[target.x86_64-unknown-linux-gnu]
# See https://github.com/PyO3/maturin-action/blob/main/src/index.ts
image = "quay.io/pypa/manylinux2014_x86_64:latest"

[target.x86_64-unknown-linux-musl]
image = 'ghcr.io/rust-cross/rust-musl-cross:x86_64-musl'

